version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: example
      DB_NAME: shopping_cart
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: shopping_cart
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
