version: '3.8'

services:
  app:
    build: ./backend
    command: npm start  # Ensure this is the correct start command
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - mynetwork
    environment:
      - NODE_ENV=production  # Set NODE_ENV to production
    restart: unless-stopped  # Restart policy

  db:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mydatabase  # Create the database
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  db_data:
